// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230924052947_TestResetBackToNormal")]
    partial class TestResetBackToNormal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<Guid>("BookForeignKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreForeignKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookForeignKey", "GenreForeignKey");

                    b.HasIndex("GenreForeignKey");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("Entities.Models.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("0cabada2-7f0c-45bb-8440-c9b3cf8c3972"),
                            Biography = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatatnon proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Birthdate = new DateTime(1920, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Frank Herbert"
                        },
                        new
                        {
                            AuthorId = new Guid("0a0f05b1-3dd9-4121-9b67-b6c0b609d748"),
                            Birthdate = new DateTime(1965, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Doe"
                        },
                        new
                        {
                            AuthorId = new Guid("44ddfe62-bd28-403f-9825-533f5f90e93f"),
                            Biography = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatatnon proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Birthdate = new DateTime(1995, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jeff Willis"
                        },
                        new
                        {
                            AuthorId = new Guid("6cf4f63f-0167-4395-81f4-bb5c4969a622"),
                            Biography = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Birthdate = new DateTime(1955, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jennifer Smith"
                        },
                        new
                        {
                            AuthorId = new Guid("9aed9ba0-83a6-4b0f-b409-2401ab3e59bf"),
                            Birthdate = new DateTime(2000, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Jones"
                        },
                        new
                        {
                            AuthorId = new Guid("afc764d1-9a45-4104-a10d-5626b39d770a"),
                            Biography = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Birthdate = new DateTime(1983, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rico Rodriguez"
                        },
                        new
                        {
                            AuthorId = new Guid("f6633cae-34f2-48e0-a87a-825747490d0b"),
                            Birthdate = new DateTime(1975, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ashley Louis"
                        },
                        new
                        {
                            AuthorId = new Guid("4050a949-3f77-43ec-8b3a-ac71bf23b5bd"),
                            Biography = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Birthdate = new DateTime(1988, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jerry Williams"
                        });
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("3c51ad1c-66e6-4daa-a20e-5c2e72c59802"),
                            Availability = true,
                            BookTitle = "Dune",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ISBN = "9780233660615",
                            PageCount = 894,
                            PublicationDate = new DateTime(1990, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("67d77f42-be53-4e4d-ac30-0b3010cdd7a2")
                        },
                        new
                        {
                            BookId = new Guid("6e8b727f-ecde-4876-916d-e81f12dfa3be"),
                            Availability = true,
                            BookTitle = "Dune",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            ISBN = "9780233660615",
                            PageCount = 894,
                            PublicationDate = new DateTime(1990, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("67d77f42-be53-4e4d-ac30-0b3010cdd7a2")
                        },
                        new
                        {
                            BookId = new Guid("a2bb0fd5-5d9b-4b11-a3a3-4948b2f1a5c5"),
                            Availability = true,
                            BookTitle = "The Catcher in the Rye",
                            ISBN = "9787360328388",
                            PageCount = 510,
                            PublicationDate = new DateTime(1980, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("3bc0b331-5b25-49a4-a86c-c7d2142f0032")
                        },
                        new
                        {
                            BookId = new Guid("c79f76c0-8409-4d73-a830-9ece06fb078d"),
                            Availability = true,
                            BookTitle = "The Catcher in the Rye",
                            ISBN = "9787360328388",
                            PageCount = 510,
                            PublicationDate = new DateTime(1980, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("3bc0b331-5b25-49a4-a86c-c7d2142f0032")
                        },
                        new
                        {
                            BookId = new Guid("a499294c-5f69-404f-91b7-c85db7f0a330"),
                            Availability = false,
                            BookTitle = "The Catcher in the Rye",
                            ISBN = "9787360328388",
                            PageCount = 510,
                            PublicationDate = new DateTime(1980, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("3bc0b331-5b25-49a4-a86c-c7d2142f0032")
                        },
                        new
                        {
                            BookId = new Guid("9a2aa24e-19d4-4cbe-bf90-96d625d012e0"),
                            Availability = true,
                            BookTitle = "Sample SciFi",
                            ISBN = "9780277097484",
                            PageCount = 421,
                            PublicationDate = new DateTime(1994, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("a1a4734d-cb76-41b2-92ef-237ff61c660a")
                        },
                        new
                        {
                            BookId = new Guid("33d274bd-2d9d-472a-b595-4ff4d0bf8c87"),
                            Availability = true,
                            BookTitle = "Sample Horror",
                            ISBN = "9781677732098",
                            PageCount = 710,
                            PublicationDate = new DateTime(2010, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("327da642-0cdd-4dde-8adc-2cfb1a90795e")
                        },
                        new
                        {
                            BookId = new Guid("1be983b8-34cc-41bf-aad0-ff83113c1ca6"),
                            Availability = true,
                            BookTitle = "Sample ScienceHistory",
                            ISBN = "9783981372724",
                            PageCount = 543,
                            PublicationDate = new DateTime(2004, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = new Guid("3bc0b331-5b25-49a4-a86c-c7d2142f0032")
                        });
                });

            modelBuilder.Entity("Entities.Models.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthor");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("33d274bd-2d9d-472a-b595-4ff4d0bf8c87"),
                            AuthorId = new Guid("9aed9ba0-83a6-4b0f-b409-2401ab3e59bf")
                        },
                        new
                        {
                            BookId = new Guid("33d274bd-2d9d-472a-b595-4ff4d0bf8c87"),
                            AuthorId = new Guid("afc764d1-9a45-4104-a10d-5626b39d770a")
                        },
                        new
                        {
                            BookId = new Guid("a2bb0fd5-5d9b-4b11-a3a3-4948b2f1a5c5"),
                            AuthorId = new Guid("4050a949-3f77-43ec-8b3a-ac71bf23b5bd")
                        },
                        new
                        {
                            BookId = new Guid("9a2aa24e-19d4-4cbe-bf90-96d625d012e0"),
                            AuthorId = new Guid("6cf4f63f-0167-4395-81f4-bb5c4969a622")
                        },
                        new
                        {
                            BookId = new Guid("3c51ad1c-66e6-4daa-a20e-5c2e72c59802"),
                            AuthorId = new Guid("0cabada2-7f0c-45bb-8440-c9b3cf8c3972")
                        },
                        new
                        {
                            BookId = new Guid("1be983b8-34cc-41bf-aad0-ff83113c1ca6"),
                            AuthorId = new Guid("44ddfe62-bd28-403f-9825-533f5f90e93f")
                        },
                        new
                        {
                            BookId = new Guid("1be983b8-34cc-41bf-aad0-ff83113c1ca6"),
                            AuthorId = new Guid("f6633cae-34f2-48e0-a87a-825747490d0b")
                        },
                        new
                        {
                            BookId = new Guid("1be983b8-34cc-41bf-aad0-ff83113c1ca6"),
                            AuthorId = new Guid("0a0f05b1-3dd9-4121-9b67-b6c0b609d748")
                        },
                        new
                        {
                            BookId = new Guid("a499294c-5f69-404f-91b7-c85db7f0a330"),
                            AuthorId = new Guid("4050a949-3f77-43ec-8b3a-ac71bf23b5bd")
                        },
                        new
                        {
                            BookId = new Guid("c79f76c0-8409-4d73-a830-9ece06fb078d"),
                            AuthorId = new Guid("4050a949-3f77-43ec-8b3a-ac71bf23b5bd")
                        },
                        new
                        {
                            BookId = new Guid("6e8b727f-ecde-4876-916d-e81f12dfa3be"),
                            AuthorId = new Guid("0cabada2-7f0c-45bb-8440-c9b3cf8c3972")
                        });
                });

            modelBuilder.Entity("Entities.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = new Guid("08e95852-2773-4d33-bed7-0383215ab34a"),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = new Guid("c40c9712-afd0-45e9-ad11-6b492933d633"),
                            Name = "Fiction"
                        },
                        new
                        {
                            GenreId = new Guid("290151b2-22b3-401e-a628-89daa9ec3541"),
                            Name = "History"
                        },
                        new
                        {
                            GenreId = new Guid("2f6ca172-ebe6-4111-9dc4-e631c9eae4ce"),
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            GenreId = new Guid("607f26b3-33ae-44c3-923a-87925e640946"),
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = new Guid("8dd47f81-c0b8-4d69-98c4-792d42d34a22"),
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = new Guid("2f8d230d-ce38-46e7-8ac4-6227d98d6d17"),
                            Name = "Science"
                        },
                        new
                        {
                            GenreId = new Guid("49c7e571-ff92-418d-8923-b5f069540749"),
                            Name = "Novel"
                        },
                        new
                        {
                            GenreId = new Guid("0d38c13b-451b-4ffe-9d6f-3949e43604ac"),
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = new Guid("8a86eddd-6fa0-4ef5-a0d4-1984254ab3ff"),
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("Entities.Models.Publisher", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            PublisherId = new Guid("a1a4734d-cb76-41b2-92ef-237ff61c660a"),
                            ContactInfo = "penguinpublishing@gmail.com",
                            Location = "USA",
                            Name = "Penguin Random House"
                        },
                        new
                        {
                            PublisherId = new Guid("3bc0b331-5b25-49a4-a86c-c7d2142f0032"),
                            ContactInfo = "contactscholastic@gmail.com",
                            Location = "France",
                            Name = "Scholastic"
                        },
                        new
                        {
                            PublisherId = new Guid("67d77f42-be53-4e4d-ac30-0b3010cdd7a2"),
                            ContactInfo = "personpublishing@gmail.com",
                            Location = "Germany",
                            Name = "Pearson"
                        },
                        new
                        {
                            PublisherId = new Guid("327da642-0cdd-4dde-8adc-2cfb1a90795e"),
                            Name = "Houghton Mifflin"
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Entities.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.HasOne("Entities.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Entities.Models.BookAuthor", b =>
                {
                    b.HasOne("Entities.Models.Author", null)
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Book", null)
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Entities.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
